# Generated by Django 3.2.6 on 2021-08-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210827_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descriptions',
            new_name='description',
        ),
    ]
